### ISSUE TITLE
Can not build raydp with Java

### ISSUE THREAD

**Issue by valiantljk** [Intel-bigdata/oap-raydp#64]
When I enable Java for Ray, I couldn't build it successfully on MacOS

```
cd oap-raydp/dev/.tmp_dir/ray/python
export RAY_INSTALL_JAVA=1
python3 setup.py -q bdist_wheel
```
The errors are:
```
INFO: Analyzed 2 targets (2 packages loaded, 484 targets configured).
INFO: Found 2 targets...
ERROR: /oap-raydp/dev/.tmp_dir/ray/BUILD.bazel:1818:10: C++ compilation of rule '//:libcore_worker_library_java.so' failed (Exit 1): cc_wrapper.sh failed: error executing command
```
and 
```
Use --sandbox_debug to see verbose messages from the sandbox
In file included from src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc:17:
src/ray/core_worker/lib/java/jni_utils.h:341:20: error: loop variable 'item' is always a copy because the range of type 'const std::vector<bool>' does not return a reference [-Werror,-Wrange-loop-analysis]
```

```
1 error generated.
INFO: Elapsed time: 24.630s, Critical Path: 24.28s
INFO: 13 processes: 10 internal, 3 darwin-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "setup.py", line 440, in <module>
    setuptools.setup(
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/Users/dr6jl/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/dr6jl/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/dr6jl/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/Users/dr6jl/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/dr6jl/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/dr6jl/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/dr6jl/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/dr6jl/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 433, in run
    return pip_run(self)
  File "setup.py", line 342, in pip_run
    build(True, BUILD_JAVA)
  File "setup.py", line 299, in build
    return bazel_invoke(
  File "setup.py", line 185, in bazel_invoke
    result = invoker([cmd] + cmdline, *args, **kwargs)
  File "/Users/dr6jl/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--verbose_failures', '--', '//:ray_pkg', '//java:ray_java_pkg']' returned non-zero exit status 1.
```
If I disable Java, the wheel can be built. But in the examples, I couldn't run this:

`ray.init(include_java=True)`

**Comment by ConeyLiu** [comment]
Hi @valiantljk, are you build as follows:
```
# build patched spark, based on spark 3.0
export RAYDP_BUILD_PYSPARK=1
# build patched ray, based on ray 0.8.7
export RAYDP_BUILD_RAY=1
${RAYDP_HOME}/.build.sh
```

We currently depend on modified ray 0.8.7 and spark.3.0.

**Comment by valiantljk** [comment]
> Hi @valiantljk, are you build as follows:
> 
> ```
> # build patched spark, based on spark 3.0
> export RAYDP_BUILD_PYSPARK=1
> # build patched ray, based on ray 0.8.7
> export RAYDP_BUILD_RAY=1
> ${RAYDP_HOME}/.build.sh
> ```
> 
> We currently depend on modified ray 0.8.7 and spark.3.0.
Yes, I followed those steps separately, i.e.,

-  build_pyspark_with_patch.sh
-  build_ray_with_patch.sh
-  mvn clean package -q -DskipTests
- python setup.py bdist_wheel

**Comment by ConeyLiu** [comment]
Hi @valiantljk, can you provide the full log, do you have already installed bazel before? It seems like bazel build java part failed. Maybe the bazel version is incompatible with ray required.

**Comment by ConeyLiu** [comment]
OK, it is the ray bug: https://github.com/ray-project/ray/pull/9907

**Comment by valiantljk** [comment]
Thanks @ConeyLiu. I just tried, and it fixed the issue. But there seems to be another bug:
```
Execution platform: @local_config_platform//:host
streaming/java/streaming-runtime/src/main/java/io/ray/streaming/runtime/transfer/ChannelId.java:144: error: [PreconditionsInvalidPlaceholder] Preconditions only accepts the %s placeholder in error message strings
        "fromTaskId %d is larger than %d", fromTaskId, Short.MAX_VALUE);
        ^
    (see https://errorprone.info/bugpattern/PreconditionsInvalidPlaceholder)
  Did you mean '"fromTaskId %s is larger than %s", fromTaskId, Short.MAX_VALUE);'?
streaming/java/streaming-runtime/src/main/java/io/ray/streaming/runtime/transfer/ChannelId.java:146: error: [PreconditionsInvalidPlaceholder] Preconditions only accepts the %s placeholder in error message strings
        "toTaskId %d is larger than %d", fromTaskId, Short.MAX_VALUE);
        ^
    (see https://errorprone.info/bugpattern/PreconditionsInvalidPlaceholder)
  Did you mean '"toTaskId %s is larger than %s", fromTaskId, Short.MAX_VALUE);'?
INFO: Elapsed time: 5.349s, Critical Path: 5.01s
INFO: 13 processes: 13 internal.
FAILED: Build did NOT complete successfully
```

**Comment by valiantljk** [comment]
Ok, I made the following changes, it seems working.

In file streaming/java/streaming-runtime/src/main/java/io/ray/streaming/runtime/transfer/ChannelId.java
Change line 143-146
from 
```
    Preconditions.checkArgument(fromTaskId < Short.MAX_VALUE,
        "fromTaskId %d is larger than %d", fromTaskId, Short.MAX_VALUE);
    Preconditions.checkArgument(toTaskId < Short.MAX_VALUE,
        "toTaskId %d is larger than %d", fromTaskId, Short.MAX_VALUE);
  
```
to
```
    Preconditions.checkArgument(fromTaskId < Short.MAX_VALUE,
        "fromTaskId %s is larger than %s", fromTaskId, Short.MAX_VALUE);
    Preconditions.checkArgument(toTaskId < Short.MAX_VALUE,
        "toTaskId %s is larger than %s", fromTaskId, Short.MAX_VALUE);
   
```
