### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by valiantljk** [Intel-bigdata/oap-raydp#69]
I followed the README to install RayDP. 
Got error when running ./build.sh
```
+ python setup.py bdist_wheel
  File "setup.py", line 31
    JARS_PATH = glob.glob(os.path.join(CORE_DIR, f"target/raydp-*.jar"))
                                                                     ^invalid syntax
```

I have:
- Python: 3.8
- Bazel 3.7.0-homebrew
- Jdk-15.0.1.jdk
- Mac: 10.15

Then I just manually re-run the python setup.py and it seems ok:
```
python setup.py bdist_wheel
```

And I copied all wheels in dist/
```
ls 
pyspark-3.0.0-py2.py3-none-any.whl        spark
raydp-0.1.dev0-py2.py3-none-any.whl
```

And installed RayDP and PySpark with pip:
```
pip install raydp-0.1.dev0-py2.py3-none-any.whl
pip install pyspark-3.0.0-py2.py3-none-any.whl
```

Then I run the following code on terminal:
```
import ray
import os
import pandas as pd, numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F

from pyspark.sql.functions import *

import raydp
from raydp.torch.estimator import TorchEstimator
from raydp.utils import random_split

ray.init()
app_name = "NYC Taxi Fare Prediction with RayDP"
num_executors = 4
cores_per_executor = 1
memory_per_executor = "1GB"
spark = raydp.init_spark(app_name, num_executors, cores_per_executor, memory_per_executor)
```

Got this error:

```
>>> spark = raydp.init_spark(app_name, num_executors, cores_per_executor, memory_per_executor)
File descriptor limit 256 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
2020-11-30 11:56:36,039	INFO services.py:1169 -- View the Ray dashboard at http://127.0.0.1:8265
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/jars/ray_dist.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/dr6jl/anaconda3/lib/python3.8/site-packages/pyspark/jars/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/Users/dr6jl/anaconda3/lib/python3.8/site-packages/pyspark/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-11-30 11:56:40 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/usr/local/Cellar/apache-spark/3.0.1/libexec/jars/spark-unsafe_2.12-3.0.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
	at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:936)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:238)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:871)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/worker.py", line 856, in custom_excepthook
    ray.state.state.add_worker(worker_id, worker_type, worker_info)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/state.py", line 733, in add_worker
    return self.global_state_accessor.add_worker_info(
AttributeError: 'NoneType' object has no attribute 'add_worker_info'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/raydp/context.py", line 121, in init_spark
    return _global_spark_context.get_or_create_session()
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/raydp/context.py", line 69, in get_or_create_session
    self._spark_session = spark_cluster.get_spark_session(
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/raydp/spark/ray_cluster.py", line 64, in get_spark_session
    spark_builder.appName(app_name).master(self.get_cluster_url()).getOrCreate()
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/pyspark/sql/session.py", line 186, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/pyspark/context.py", line 371, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/pyspark/context.py", line 128, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/pyspark/context.py", line 320, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/pyspark/java_gateway.py", line 105, in launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
```

**Comment by ConeyLiu** [comment]
hi @valiantljk 
```python
+ python setup.py bdist_wheel
  File "setup.py", line 31
    JARS_PATH = glob.glob(os.path.join(CORE_DIR, f"target/raydp-*.jar"))
                                                                     ^invalid syntax
```

The f string should work with python 3.8.  However, the error message comes from when the python version is smaller than python 3.6. I tested locally with python 3.8.0 and it works. Could you check your python version again?

```java
Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
```
This error means your `pyspark` has not built with our patch. 
when you build with the following:
```
# build patched spark, based on spark 3.0
export RAYDP_BUILD_PYSPARK=1
${RAYDP_HOME}/.build.sh
```

Have you see the following prints:
```
+ pushd spark
~/git/raydp/dev/.tmp_dir/spark ~/git/raydp/dev/.tmp_dir ~/git/raydp/dev ~/git/raydp
+ git reset --hard 3fdfce3120f307147244e5eaf46d61419a723d50
HEAD is now at 3fdfce3120 Preparing Spark release v3.0.0-rc3
+ git apply --check /Users/xianyang/git/raydp/dev/spark.patch
+ git am /Users/xianyang/git/raydp/dev/spark.patch
Applying: add user defined resource manager support
+ mvn clean package -q -DskipTests
```

or you maybe need `pip uninstall pyspark` and then install the pyspark under the `dist` folder one.

**Comment by valiantljk** [comment]
Yes, I have seen the same outputs:

```
Resolving deltas: 100% (239671/239671), done.
Updating files: 100% (16250/16250), done.
+ pushd spark
~/Documents/oap-raydp/dev/.tmp_dir/spark ~/Documents/oap-raydp/dev/.tmp_dir ~/Documents/oap-raydp/dev ~/Documents/oap-raydp
+ git reset --hard 3fdfce3120f307147244e5eaf46d61419a723d50
HEAD is now at 3fdfce3120 Preparing Spark release v3.0.0-rc3
+ git apply --check /Users/dr6jl/Documents/oap-raydp/dev/spark.patch
+ git am /Users/dr6jl/Documents/oap-raydp/dev/spark.patch
Applying: add user defined resource manager support
+ mvn clean package -q -DskipTests
+ pushd python
...
```
And I uninstalled PySpark before re-installing. 
Still got the error:

```
Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
	at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:936)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:238)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:871)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/worker.py", line 856, in custom_excepthook
    ray.state.state.add_worker(worker_id, worker_type, worker_info)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/state.py", line 733, in add_worker
    return self.global_state_accessor.add_worker_info(
```

> Have you see the following prints:
> 
> ```
> + pushd spark
> ~/git/raydp/dev/.tmp_dir/spark ~/git/raydp/dev/.tmp_dir ~/git/raydp/dev ~/git/raydp
> + git reset --hard 3fdfce3120f307147244e5eaf46d61419a723d50
> HEAD is now at 3fdfce3120 Preparing Spark release v3.0.0-rc3
> + git apply --check /Users/xianyang/git/raydp/dev/spark.patch
> + git am /Users/xianyang/git/raydp/dev/spark.patch
> Applying: add user defined resource manager support
> + mvn clean package -q -DskipTests
> ```
> 
> or you maybe need `pip uninstall pyspark` and then install the pyspark under the `dist` folder one.

**Comment by valiantljk** [comment]
I confirmed that the Spark code has been patched, 

```
      case _ => OTHERS
//        error("Master must either be yarn or start with spark, mesos, k8s, or local")
//        -1
```

It's weird that the error still complains about it
```
 in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
```

**Comment by ConeyLiu** [comment]
Do you have set `SPARK_HOME` env?

**Comment by valiantljk** [comment]
> Do you have set `SPARK_HOME` env?

Nope, how to set it?

**Comment by ConeyLiu** [comment]
You could print in shell with:
```shell
echo ${SPARK_HOME}
```

or check in ipython:
```python
import pyspark
import os

print(pyspark.__file__)  # see whether it is the one you installed
print(os.environ.get("SPARK_HOME", "Not set")  # whether has set env and point to where

```

**Comment by valiantljk** [comment]
Turns out I have previously installed spark..
Setting the SPARK_HOME to dist/spark solved the issue. 

Thanks @ConeyLiu !
The issue can be closed.
