### ISSUE TITLE
Error when running estimator.fit_on_spark()

### ISSUE THREAD

**Issue by valiantljk** [Intel-bigdata/oap-raydp#72]
I was able to run all the steps following the pytorch example, until:

```
# Train the model
estimator.fit_on_spark(train_df, test_df)
```

Got this error:
```
2020-12-01 00:03:26,525	WARNING worker.py:1031 -- Failed to unpickle actor class 'DistributedTorchRunner' for actor ID 62223d8501000000. Traceback:
Traceback (most recent call last):
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/function_manager.py", line 494, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/util/sgd/__init__.py", line 1, in <module>
    from ray.util.sgd.torch import TorchTrainer
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/util/sgd/torch/__init__.py", line 12, in <module>
    from ray.util.sgd.torch.torch_trainer import (TorchTrainer,
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/util/sgd/torch/torch_trainer.py", line 13, in <module>
    from ray.tune import Trainable
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/__init__.py", line 2, in <module>
    from ray.tune.tune import run_experiments, run
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/tune.py", line 13, in <module>
    from ray.tune.ray_trial_executor import RayTrialExecutor
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 15, in <module>
    from ray.tune.durable_trainable import DurableTrainable
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/durable_trainable.py", line 5, in <module>
    from ray.tune.syncer import get_cloud_sync_client
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/ray/tune/syncer.py", line 90, in <module>
    class SyncConfig:
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/dataclasses.py", line 800, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/Users/dr6jl/anaconda3/lib/python3.8/site-packages/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'
```

**Comment by ConeyLiu** [comment]
Could you try `pip uninstall dataclasses`. It seems the dataclasses not compatible with python 3.8.

**Comment by ConeyLiu** [comment]
This should be closed.
